all:
  hosts:
    master:
      ansible_host: 192.168.56.101
      ansible_user: phuc
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_user: root
      ansible_become_password: "123"
      ip: 192.168.56.101
      access_ip: 192.168.56.101
    worker:
      ansible_host: 192.168.56.102
      ansible_user: phuc
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_user: root
      ansible_become_password: "123"
      ip: 192.168.56.102
      access_ip: 192.168.56.102
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
