loki:
  auth_enabled: false
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 5Gi
      storageClass: local-path
      accessMode: ReadWriteOnce
  storage:
    type: s3
    s3:
      endpoint: minio.monitoring.svc.cluster.local:9000
      region: us-east-1
      bucketnames:
        chunks: loki-chunks
        ruler: loki-ruler
      access_key_id: minioadmin
      secret_access_key: minioadmin123
      s3forcepathstyle: true
      insecure: true

# Disable other components
gateway:
  enabled: false

grafana-agent-operator:
  enabled: false

canary:
  enabled: false

logs:
  enabled: false

service:
  type: LoadBalancer

ingress:
  enabled: true
  hosts:
    - loki.local
  ingressClassName: nginx 