# Kubernetes Cluster Configuration
kube_version: v1.28.5
container_manager: containerd
dns_mode: coredns
helm_enabled: true
metrics_server_enabled: true

# Calico CNI Configuration
kube_network_plugin: calico
calico_version: v3.26.1
calico_typha_enabled: false
calico_typha_replicas: 0

# Network Configuration
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24

# Calico IP Pool Configuration
calico_ip_auto_method: "kubernetes-internal-ip"
calico_ipv4pool_cidr: "10.233.64.0/18"
calico_ipv4pool_ipip: "CrossSubnet"
calico_ipv4pool_vxlan: "Never"

# Security Configuration
podsecuritypolicy_enabled: false
kubernetes_audit: false

# Addon Configuration
dashboard_enabled: false
registry_enabled: false

# Container Runtime Configuration
containerd_use_systemd_cgroup: true

# Load Balancer Configuration (Optional)
loadbalancer_apiserver:
  address: 192.168.56.101
  port: 6443

# Node Configuration
kubelet_cgroup_driver: systemd
kubelet_eviction_hard: "memory.available<100Mi,nodefs.available<10%"
kubelet_eviction_soft: "memory.available<200Mi,nodefs.available<15%"
kubelet_eviction_soft_grace_period: "memory.available=30s,nodefs.available=30s" 